DROP DATABASE IF EXISTS wp;
DROP USER  `wpadmin`@`%`;
DROP USER `wpuser`@`%`;
CREATE DATABASE wp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER  `wpadmin`@`%` IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `wp`.* TO `wpadmin`@`%`;
CREATE USER  `wpuser`@`%` IDENTIFIED  BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `wp`.* TO `wpuser`@`%`;
FLUSH PRIVILEGES;